# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestQA():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_qA(self):
    self.driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("Admin")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("admin123")
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button").click()
    time.sleep(10)
    self.driver.find_element(By.LINK_TEXT, "Recruitment").click()
    time.sleep(10)
    element = self.driver.find_element(By.CSS_SELECTOR, ".active > .oxd-text")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".bi-plus").click()
    time.sleep(2)
    self.driver.find_element(By.NAME, "firstName").click()
    self.driver.find_element(By.NAME, "firstName").send_keys("Pedro")
    self.driver.find_element(By.NAME, "middleName").click()
    self.driver.find_element(By.NAME, "middleName").send_keys("Miguel")
    self.driver.find_element(By.NAME, "lastName").click()
    self.driver.find_element(By.NAME, "lastName").send_keys("Serrano")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-select-text--after").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".oxd-select-dropdown")))
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-select-dropdown > div:nth-child(3)").click()
    time.sleep(2)
    self.driver.find_element(By.XPATH, "//*[@id=\"app\"]/div[1]/div[2]/div[2]/div/div/form/div[3]/div/div[1]/div/div[2]/input").send_keys("prueba@gmail.com")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--secondary").click()
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--success").click()
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--secondary").click()
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--success").click()
    time.sleep(10)
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div[2]/div[2]/div/div/form/div[2]/div/div/div/div[2]/input").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div[2]/div[2]/div/div/form/div[2]/div/div/div/div[2]/input").send_keys("Prueba")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-autocomplete-text-input > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-autocomplete-text-input > input").send_keys("1")
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".oxd-autocomplete-dropdown")))
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-autocomplete-dropdown > div:nth-child(4)").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div[2]/div[2]/div/div/form/div[2]/div/div[3]/div/div[2]/div/div/input").click()
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-calendar-date-wrapper:nth-child(13) > .oxd-calendar-date").click()
    time.sleep(5)
    self.driver.find_element(By.XPATH, "//*[@id=\"app\"]/div[1]/div[2]/div[2]/div/div/form/div[2]/div/div[4]/div/div[2]/div/div/input").click()
    self.driver.find_element(By.NAME, "pm").click()
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--secondary").click()
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--success").click()
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--secondary").click()
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button:nth-child(3)").click()
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--secondary").click()
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--success").click()
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--secondary").click()
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-table-card:nth-child(1) .oxd-table-cell:nth-child(1)").click()
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-userdropdown-name").click()
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(4) > .oxd-userdropdown-link").click()
    time.sleep(10)
    self.driver.close()
  
